// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sentinel.proto
#ifndef GRPC_sentinel_2eproto__INCLUDED
#define GRPC_sentinel_2eproto__INCLUDED

#include "sentinel.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace sentinel {

// The Service: Functions the Server exposes
class MetricsService final {
 public:
  static constexpr char const* service_full_name() {
    return "sentinel.MetricsService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Client streams data to Server (Stream -> Server)
    std::unique_ptr< ::grpc::ClientWriterInterface< ::sentinel::MetricData>> ReportMetrics(::grpc::ClientContext* context, ::sentinel::Empty* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::sentinel::MetricData>>(ReportMetricsRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::sentinel::MetricData>> AsyncReportMetrics(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::sentinel::MetricData>>(AsyncReportMetricsRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::sentinel::MetricData>> PrepareAsyncReportMetrics(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::sentinel::MetricData>>(PrepareAsyncReportMetricsRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Client streams data to Server (Stream -> Server)
      virtual void ReportMetrics(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::ClientWriteReactor< ::sentinel::MetricData>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::sentinel::MetricData>* ReportMetricsRaw(::grpc::ClientContext* context, ::sentinel::Empty* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::sentinel::MetricData>* AsyncReportMetricsRaw(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::sentinel::MetricData>* PrepareAsyncReportMetricsRaw(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::sentinel::MetricData>> ReportMetrics(::grpc::ClientContext* context, ::sentinel::Empty* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::sentinel::MetricData>>(ReportMetricsRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::sentinel::MetricData>> AsyncReportMetrics(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::sentinel::MetricData>>(AsyncReportMetricsRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::sentinel::MetricData>> PrepareAsyncReportMetrics(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::sentinel::MetricData>>(PrepareAsyncReportMetricsRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ReportMetrics(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::ClientWriteReactor< ::sentinel::MetricData>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::sentinel::MetricData>* ReportMetricsRaw(::grpc::ClientContext* context, ::sentinel::Empty* response) override;
    ::grpc::ClientAsyncWriter< ::sentinel::MetricData>* AsyncReportMetricsRaw(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::sentinel::MetricData>* PrepareAsyncReportMetricsRaw(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ReportMetrics_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Client streams data to Server (Stream -> Server)
    virtual ::grpc::Status ReportMetrics(::grpc::ServerContext* context, ::grpc::ServerReader< ::sentinel::MetricData>* reader, ::sentinel::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportMetrics() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ReportMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportMetrics(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sentinel::MetricData>* /*reader*/, ::sentinel::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportMetrics(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::sentinel::Empty, ::sentinel::MetricData>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ReportMetrics<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ReportMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportMetrics() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::sentinel::MetricData, ::sentinel::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, ::sentinel::Empty* response) { return this->ReportMetrics(context, response); }));
    }
    ~WithCallbackMethod_ReportMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportMetrics(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sentinel::MetricData>* /*reader*/, ::sentinel::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::sentinel::MetricData>* ReportMetrics(
      ::grpc::CallbackServerContext* /*context*/, ::sentinel::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ReportMetrics<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ReportMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportMetrics() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ReportMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportMetrics(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sentinel::MetricData>* /*reader*/, ::sentinel::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportMetrics() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ReportMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportMetrics(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sentinel::MetricData>* /*reader*/, ::sentinel::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportMetrics(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportMetrics() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->ReportMetrics(context, response); }));
    }
    ~WithRawCallbackMethod_ReportMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportMetrics(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::sentinel::MetricData>* /*reader*/, ::sentinel::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* ReportMetrics(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace sentinel


#endif  // GRPC_sentinel_2eproto__INCLUDED
