// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sentinel.proto

#include "sentinel.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace sentinel {
PROTOBUF_CONSTEXPR MetricData::MetricData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.agent_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.cpu_usage_)*/0
  , /*decltype(_impl_.ram_usage_)*/0
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MetricDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MetricDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MetricDataDefaultTypeInternal() {}
  union {
    MetricData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MetricDataDefaultTypeInternal _MetricData_default_instance_;
PROTOBUF_CONSTEXPR Empty::Empty(
    ::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
}  // namespace sentinel
static ::_pb::Metadata file_level_metadata_sentinel_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sentinel_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sentinel_2eproto = nullptr;

const uint32_t TableStruct_sentinel_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sentinel::MetricData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::sentinel::MetricData, _impl_.agent_id_),
  PROTOBUF_FIELD_OFFSET(::sentinel::MetricData, _impl_.cpu_usage_),
  PROTOBUF_FIELD_OFFSET(::sentinel::MetricData, _impl_.ram_usage_),
  PROTOBUF_FIELD_OFFSET(::sentinel::MetricData, _impl_.timestamp_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sentinel::Empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::sentinel::MetricData)},
  { 10, -1, -1, sizeof(::sentinel::Empty)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::sentinel::_MetricData_default_instance_._instance,
  &::sentinel::_Empty_default_instance_._instance,
};

const char descriptor_table_protodef_sentinel_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016sentinel.proto\022\010sentinel\"W\n\nMetricData"
  "\022\020\n\010agent_id\030\001 \001(\t\022\021\n\tcpu_usage\030\002 \001(\001\022\021\n"
  "\tram_usage\030\003 \001(\001\022\021\n\ttimestamp\030\004 \001(\003\"\007\n\005E"
  "mpty2J\n\016MetricsService\0228\n\rReportMetrics\022"
  "\024.sentinel.MetricData\032\017.sentinel.Empty(\001"
  "b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_sentinel_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sentinel_2eproto = {
    false, false, 208, descriptor_table_protodef_sentinel_2eproto,
    "sentinel.proto",
    &descriptor_table_sentinel_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_sentinel_2eproto::offsets,
    file_level_metadata_sentinel_2eproto, file_level_enum_descriptors_sentinel_2eproto,
    file_level_service_descriptors_sentinel_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sentinel_2eproto_getter() {
  return &descriptor_table_sentinel_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sentinel_2eproto(&descriptor_table_sentinel_2eproto);
namespace sentinel {

// ===================================================================

class MetricData::_Internal {
 public:
};

MetricData::MetricData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:sentinel.MetricData)
}
MetricData::MetricData(const MetricData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MetricData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.agent_id_){}
    , decltype(_impl_.cpu_usage_){}
    , decltype(_impl_.ram_usage_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.agent_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.agent_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_agent_id().empty()) {
    _this->_impl_.agent_id_.Set(from._internal_agent_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.cpu_usage_, &from._impl_.cpu_usage_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timestamp_) -
    reinterpret_cast<char*>(&_impl_.cpu_usage_)) + sizeof(_impl_.timestamp_));
  // @@protoc_insertion_point(copy_constructor:sentinel.MetricData)
}

inline void MetricData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.agent_id_){}
    , decltype(_impl_.cpu_usage_){0}
    , decltype(_impl_.ram_usage_){0}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.agent_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.agent_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MetricData::~MetricData() {
  // @@protoc_insertion_point(destructor:sentinel.MetricData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MetricData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.agent_id_.Destroy();
}

void MetricData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MetricData::Clear() {
// @@protoc_insertion_point(message_clear_start:sentinel.MetricData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.agent_id_.ClearToEmpty();
  ::memset(&_impl_.cpu_usage_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.cpu_usage_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MetricData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string agent_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_agent_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "sentinel.MetricData.agent_id"));
        } else
          goto handle_unusual;
        continue;
      // double cpu_usage = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.cpu_usage_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double ram_usage = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.ram_usage_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MetricData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sentinel.MetricData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string agent_id = 1;
  if (!this->_internal_agent_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_agent_id().data(), static_cast<int>(this->_internal_agent_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "sentinel.MetricData.agent_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_agent_id(), target);
  }

  // double cpu_usage = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_cpu_usage = this->_internal_cpu_usage();
  uint64_t raw_cpu_usage;
  memcpy(&raw_cpu_usage, &tmp_cpu_usage, sizeof(tmp_cpu_usage));
  if (raw_cpu_usage != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_cpu_usage(), target);
  }

  // double ram_usage = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_ram_usage = this->_internal_ram_usage();
  uint64_t raw_ram_usage;
  memcpy(&raw_ram_usage, &tmp_ram_usage, sizeof(tmp_ram_usage));
  if (raw_ram_usage != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_ram_usage(), target);
  }

  // int64 timestamp = 4;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sentinel.MetricData)
  return target;
}

size_t MetricData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sentinel.MetricData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string agent_id = 1;
  if (!this->_internal_agent_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_agent_id());
  }

  // double cpu_usage = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_cpu_usage = this->_internal_cpu_usage();
  uint64_t raw_cpu_usage;
  memcpy(&raw_cpu_usage, &tmp_cpu_usage, sizeof(tmp_cpu_usage));
  if (raw_cpu_usage != 0) {
    total_size += 1 + 8;
  }

  // double ram_usage = 3;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_ram_usage = this->_internal_ram_usage();
  uint64_t raw_ram_usage;
  memcpy(&raw_ram_usage, &tmp_ram_usage, sizeof(tmp_ram_usage));
  if (raw_ram_usage != 0) {
    total_size += 1 + 8;
  }

  // int64 timestamp = 4;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MetricData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MetricData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MetricData::GetClassData() const { return &_class_data_; }


void MetricData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MetricData*>(&to_msg);
  auto& from = static_cast<const MetricData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sentinel.MetricData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_agent_id().empty()) {
    _this->_internal_set_agent_id(from._internal_agent_id());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_cpu_usage = from._internal_cpu_usage();
  uint64_t raw_cpu_usage;
  memcpy(&raw_cpu_usage, &tmp_cpu_usage, sizeof(tmp_cpu_usage));
  if (raw_cpu_usage != 0) {
    _this->_internal_set_cpu_usage(from._internal_cpu_usage());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_ram_usage = from._internal_ram_usage();
  uint64_t raw_ram_usage;
  memcpy(&raw_ram_usage, &tmp_ram_usage, sizeof(tmp_ram_usage));
  if (raw_ram_usage != 0) {
    _this->_internal_set_ram_usage(from._internal_ram_usage());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MetricData::CopyFrom(const MetricData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sentinel.MetricData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetricData::IsInitialized() const {
  return true;
}

void MetricData::InternalSwap(MetricData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.agent_id_, lhs_arena,
      &other->_impl_.agent_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MetricData, _impl_.timestamp_)
      + sizeof(MetricData::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(MetricData, _impl_.cpu_usage_)>(
          reinterpret_cast<char*>(&_impl_.cpu_usage_),
          reinterpret_cast<char*>(&other->_impl_.cpu_usage_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MetricData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sentinel_2eproto_getter, &descriptor_table_sentinel_2eproto_once,
      file_level_metadata_sentinel_2eproto[0]);
}

// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:sentinel.Empty)
}
Empty::Empty(const Empty& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Empty* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:sentinel.Empty)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Empty::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Empty::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sentinel_2eproto_getter, &descriptor_table_sentinel_2eproto_once,
      file_level_metadata_sentinel_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sentinel
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sentinel::MetricData*
Arena::CreateMaybeMessage< ::sentinel::MetricData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sentinel::MetricData >(arena);
}
template<> PROTOBUF_NOINLINE ::sentinel::Empty*
Arena::CreateMaybeMessage< ::sentinel::Empty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sentinel::Empty >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
