// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sentinel.proto

#include "sentinel.pb.h"
#include "sentinel.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace sentinel {

static const char* MetricsService_method_names[] = {
  "/sentinel.MetricsService/ReportMetrics",
};

std::unique_ptr< MetricsService::Stub> MetricsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MetricsService::Stub> stub(new MetricsService::Stub(channel, options));
  return stub;
}

MetricsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ReportMetrics_(MetricsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::sentinel::MetricData>* MetricsService::Stub::ReportMetricsRaw(::grpc::ClientContext* context, ::sentinel::Empty* response) {
  return ::grpc::internal::ClientWriterFactory< ::sentinel::MetricData>::Create(channel_.get(), rpcmethod_ReportMetrics_, context, response);
}

void MetricsService::Stub::async::ReportMetrics(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::ClientWriteReactor< ::sentinel::MetricData>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::sentinel::MetricData>::Create(stub_->channel_.get(), stub_->rpcmethod_ReportMetrics_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::sentinel::MetricData>* MetricsService::Stub::AsyncReportMetricsRaw(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::sentinel::MetricData>::Create(channel_.get(), cq, rpcmethod_ReportMetrics_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::sentinel::MetricData>* MetricsService::Stub::PrepareAsyncReportMetricsRaw(::grpc::ClientContext* context, ::sentinel::Empty* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::sentinel::MetricData>::Create(channel_.get(), cq, rpcmethod_ReportMetrics_, context, response, false, nullptr);
}

MetricsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< MetricsService::Service, ::sentinel::MetricData, ::sentinel::Empty>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::sentinel::MetricData>* reader,
             ::sentinel::Empty* resp) {
               return service->ReportMetrics(ctx, reader, resp);
             }, this)));
}

MetricsService::Service::~Service() {
}

::grpc::Status MetricsService::Service::ReportMetrics(::grpc::ServerContext* context, ::grpc::ServerReader< ::sentinel::MetricData>* reader, ::sentinel::Empty* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sentinel

